// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6d-VvAmZSOLaNxiaEBNfpYPuTSCWfESY',
    appId: '1:31887102833:web:02878b35fc90b939a79cd0',
    messagingSenderId: '31887102833',
    projectId: 'echo-52bef',
    authDomain: 'echo-52bef.firebaseapp.com',
    storageBucket: 'echo-52bef.firebasestorage.app',
    measurementId: 'G-KQE4081P6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNHNGGWlGN4VjBlR-k0_PvFhBXh5qYLD4',
    appId: '1:31887102833:android:940587c6a536ed68a79cd0',
    messagingSenderId: '31887102833',
    projectId: 'echo-52bef',
    storageBucket: 'echo-52bef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj9fb5IgHRABJVm6LXSrvAdyusAVOPgH0',
    appId: '1:31887102833:ios:a1dc1050a3044f88a79cd0',
    messagingSenderId: '31887102833',
    projectId: 'echo-52bef',
    storageBucket: 'echo-52bef.firebasestorage.app',
    iosBundleId: 'com.nourdev.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj9fb5IgHRABJVm6LXSrvAdyusAVOPgH0',
    appId: '1:31887102833:ios:ca246528484e6a7da79cd0',
    messagingSenderId: '31887102833',
    projectId: 'echo-52bef',
    storageBucket: 'echo-52bef.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6d-VvAmZSOLaNxiaEBNfpYPuTSCWfESY',
    appId: '1:31887102833:web:54fd75f60ddf62e1a79cd0',
    messagingSenderId: '31887102833',
    projectId: 'echo-52bef',
    authDomain: 'echo-52bef.firebaseapp.com',
    storageBucket: 'echo-52bef.firebasestorage.app',
    measurementId: 'G-XY6HSR5WD1',
  );
}
